name: Install OpenSiv3D SDK
description: Download the OpenSiv3D SDK for Windows from the URL and unpack it to the destination path.

inputs:
  download-url:
    description: Url for downloading .zip file
    required: true
  siv3d-version:
    description: OpenSiv3D version
    required: true
  destination:
    description: Installation path
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Restore Cached SDK Files
      id: restore-sdk-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.destination }}
        key: siv3d-sdk-${{ inputs.siv3d-version }}

    - name: Download SDK Zip File
      if: steps.restore-sdk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -L -o '${{ runner.temp }}/sdk.zip' '${{ inputs.download-url }}'

    - name: Extract SDK Files
      if: steps.restore-sdk-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        tmp_zippath='${{ runner.temp }}/sdk.zip'
        tmp_sdkpath=$(echo '${{ runner.temp }}/sdk' | sed 's|\\|/|g') # for cp command
        destination_path='${{ inputs.destination }}'

        unzip -d $tmp_sdkpath $tmp_zippath
        mkdir -p $destination_path
        cp -r $tmp_sdkpath/$(ls $tmp_sdkpath | head -n 1)/* $destination_path
        rm -r $tmp_sdkpath $tmp_zippath

        echo $destination_path
        ls -al $destination_path
    
    - name: Save SDK Files
      if: steps.restore-sdk-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.destination }}
        key: ${{ steps.restore-sdk-cache.outputs.cache-primary-key }}
