name: MSBuild

on:
  push:
  pull_request:
    types: [synchronize, opened]

env:
  MSBUILD_CONFIGURATION: Release

jobs:
  build_flexlayout:
    runs-on: windows-latest
    env:
      SIV3D_0_6_15: "/OpenSiv3D_0.6.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Install vcpkg MSVC integration
        run: vcpkg integrate install

      - name: Install OpenSiv3D SDK
        uses: ./.github/actions/install_siv3d
        with:
          download-url: "https://siv3d.jp/downloads/Siv3D/manual/0.6.15/OpenSiv3D_SDK_0.6.15.zip"
          siv3d-version: "0.6.15"
          destination: ${{ env.SIV3D_0_6_15 }}
      
      - name: Build FlexLayout
        run: |
          msbuild -version
          msbuild ./FlexLayout.vcxproj -m -t:build -p:configuration=${{ env.MSBUILD_CONFIGURATION }} -p:platform=x64
