name: MSBuild

on:
  push:
  pull_request:
    types: [synchronize, opened]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: test1
        shell: bash
        run: |
          pwd
          ls -al
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: test2
        shell: bash
        run: |
          pwd
          ls -al