name: MSBuild

on:
  push:
  pull_request:
    types: [synchronize, opened]

env:
  MSBUILD_CONFIGURATION: Release

jobs:
  build_flexlayout:
    runs-on: windows-latest
    env:
      SIV3D_0_6_15: "OpenSiv3D_SDK"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Install vcpkg MSVC integration
        run: vcpkg integrate install

      - name: Install OpenSiv3D SDK
        uses: ./.github/actions/install_siv3d
        with:
          download-url: "https://siv3d.jp/downloads/Siv3D/manual/0.6.15/OpenSiv3D_SDK_0.6.15.zip"
          siv3d-version: "0.6.15"
          destination: ${{ env.SIV3D_0_6_15 }}
      
      - name: Build FlexLayout
        shell: pwsh
        run: |
          $env:SIV3D_0_6_15 = "${{ env.SIV3D_0_6_15 }}"
          msbuild -version
          msbuild ./FlexLayout.vcxproj -m -t:build -p:configuration=${{ env.MSBUILD_CONFIGURATION }} -p:platform=x64
      
      - name: Print Outputs
        run: |
          Get-ChildItem -Path Build/FlexLayout/${{ env.MSBUILD_CONFIGURATION }} -File | ForEach-Object {
              $fileSizeMB = "{0:N2}" -f ($_.Length / 1MB)
              [PSCustomObject]@{
                  FileName = $_.Name
                  SizeMB   = $fileSizeMB
              }
          } | Format-Table -AutoSize

      - name: Upload Libraries
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: |
            Build/FlexLayout/${{ env.MSBUILD_CONFIGURATION }}/*.lib
            Build/FlexLayout/${{ env.MSBUILD_CONFIGURATION }}/*.pdb
          if-no-files-found: error
